cmooney-2019071101: fix proxy null error
This fixes the null dereference error below.

TypeError: Cannot read property 'toLowerCase' of null
    at EthereumCdpService._callee$ (/makerdao/makerdao-scripts/node_modules/@makerdao/dai/src/eth/EthereumCdpService.js:144:37)
    at tryCatch (/makerdao/makerdao-scripts/node_modules/regenerator-runtime/runtime.js:45:40)
    at Generator.invoke [as _invoke] (/makerdao/makerdao-scripts/node_modules/regenerator-runtime/runtime.js:271:22)
    at Generator.prototype.(anonymous function) [as next] (/makerdao/makerdao-scripts/node_modules/regenerator-runtime/runtime.js:97:21)
    at asyncGeneratorStep (/makerdao/makerdao-scripts/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (/makerdao/makerdao-scripts/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)

Since the code is transpiled, this is my best guess at the location of
the fix.  When I make this same change in the transpiled code it works
correctly.  This should resolve the bug.